---
version: '3'
services:
  consul:
    image: consul:0.8.4
    command: consul agent -dev -client 0.0.0.0
    hostname: consul
    ports:
     - "8500:8500"
     - "8600:8600/udp"

  registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    hostname: registrator
    depends_on:
     - consul
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    links:
     - consul
    security_opt:
     - label:type:docker_t

